### ISSUE TITLE
Dotplot doesn't work

### ISSUE THREAD

**Issue by aseetharam** [lpryszcz/pyScaf#1]
Hi Leszek,

I ran pyScaf to compare my genome with other closely related species. My main goal was to generate dotplots for them. I ran the command something like this:

```
python /shared/software/GIF/programs/pyscaf/2016-04-08/pyScaf.py \
    --fasta $GENOME \
    --reference $TARGET \
    --norearrangements \
    --threads 16 \
    --dotplot pdf \
    --log ${GENOME%.*}_pynast.log
```
The STDOUT showed that the job completed sucessfully:
```
Options: Namespace(dotplot='pdf', fasta='MaSuRCA_redundans_final.fasta', fastq=None, identity=0.33, joins=5, linkratio=0.7, load=0.2, log=<open file 'MaSuRCA_redundans_final_pynast.log', mode 'w' at 0x2ab415a29300>, longreads=None, mapq=10, maxgap=0, norearrangements=True, overlap=0.66, ref='Cyanidioschyzon_merolae.ASM9120v1.dna.toplevel.fa', threads=16)
 maxgap cut-off of 17978594 bp

##################################################
[Thu Nov 10 15:11:39 2016][   94 Mb] Aligning contigs on reference...

##################################################
[Thu Nov 10 15:11:39 2016][   94 Mb] Saving dotplots to: MaSuRCA_redundans_final.fasta.pdf
[WARNING] dotplot generation failed!

##################################################
[Thu Nov 10 15:19:26 2016][   94 Mb] Reporting scaffolds...
 1797859444 bp in 17040 scaffolds. Details in MaSuRCA_redundans_final.fasta.scaffolds.ref.fa.tsv
Scaffolds saved to: MaSuRCA_redundans_final.fasta.scaffolds.ref.fa

##################################################
[Thu Nov 10 15:22:17 2016][  118 Mb] Saving dotplots to: MaSuRCA_redundans_final.fasta.scaffolds.ref.fa.pdf

##################################################
[Thu Nov 10 15:22:18 2016][  118 Mb] Done!
```
except for the `[WARNING] dotplot generation failed!`.
Does this mean that I was missing some packages required to plot? Or is this the data which didn't produce any dotplot?

Thanks for the help! Have a great day!

**Comment by lpryszcz** [comment]
Hi, this is most likely due to too many contigs in your assembly. in my experience last-dotplot failed with over several hundreds contigs... 

You can try to plot it yourself using lastal or nucmer:

`# index reference genome (need to be done only once per each reference)
lastdb ../ref.fa ../ref.fa

# align & generate dotplot on the fly
lastal -f TAB ../ref.fa scaffolds.filled.fa | last-dotplot - scaffolds.filled.fa.png
`

`
# align
nucmer -p nucmer.ref ../ref.fa scaffolds.filled.fa
# generate pairwise plot
mummerplot --png --large nucmer.ref.delta -p nucmer.ref.plot
`
